






CREATE TABLE streams (
    stream_id  VARCHAR(500) NOT NULL PRIMARY KEY,
    version    BIGINT NOT NULL
);

CREATE TABLE events (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stream_id     VARCHAR(500) NOT NULL,
    version       BIGINT NOT NULL,
    event_type    VARCHAR(100) NOT NULL,
    payload_json  VARCHAR NOT NULL,
    occurred_at   TIMESTAMP NOT NULL,
    recorded_at   TIMESTAMP NOT NULL,
    CONSTRAINT uq_events_stream_version UNIQUE (stream_id, version)
);

CREATE INDEX idx_events_stream ON events (stream_id);

CREATE TABLE outbox (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stream_id     VARCHAR(500) NOT NULL,
    event_type    VARCHAR(100) NOT NULL,
    payload_json  VARCHAR NOT NULL,
    occurred_at   TIMESTAMP NOT NULL,
    published     BOOLEAN NOT NULL DEFAULT FALSE,
    published_at  TIMESTAMP,
    created_at    TIMESTAMP NOT NULL
);

CREATE INDEX idx_outbox_unpublished ON outbox (published, id);

CREATE TABLE account_balances (
    tenant_id            VARCHAR(64) NOT NULL,
    account_id           VARCHAR(64) NOT NULL,
    currency             VARCHAR(3) NOT NULL,
    balance_minor_units  BIGINT NOT NULL,
    updated_at           TIMESTAMP NOT NULL,
    PRIMARY KEY (tenant_id, account_id)
);

CREATE TABLE transaction_history (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       VARCHAR(64) NOT NULL,
    account_id      VARCHAR(64) NOT NULL,
    transaction_id  VARCHAR(64) NOT NULL,
    occurred_at     TIMESTAMP NOT NULL,
    CONSTRAINT uq_transaction_history UNIQUE (account_id, transaction_id)
);

CREATE INDEX idx_transaction_history_lookup ON transaction_history (tenant_id, account_id, occurred_at);

CREATE TABLE idempotency_reservations (
    tenant_id        VARCHAR(64) NOT NULL,
    idempotency_key  VARCHAR(200) NOT NULL,
    transaction_id   VARCHAR(64) NOT NULL,
    reserved_at      TIMESTAMP NOT NULL,
    PRIMARY KEY (tenant_id, idempotency_key)
);
