package io.castellan.apm.agent.weave.jdbc;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

import com.example.jdbcapp.FakeJdbcStatement;
import com.example.jdbcapp.FakeJdbcStatementTarget;
import com.example.jdbcapp.NotJdbc;
import io.castellan.apm.agent.weave.CapturingExporter;
import io.castellan.apm.agent.weave.CastellanClassFileTransformer;
import io.castellan.apm.agent.weave.WeavingTestSupport;
import io.castellan.apm.core.SpanData;
import io.castellan.apm.core.SpanKind;
import io.castellan.apm.core.SpanStatus;
import java.util.List;
import java.util.Set;
import org.junit.jupiter.api.Test;

/**
 * Exercises the whole ASM pipeline (probe -&gt; decide -&gt; weave -&gt; write) against a real
 * class file, per the task's required-minimum test strategy: {@link
 * CastellanClassFileTransformer#transform} is called directly (no {@code -javaagent} attach), the
 * *woven* bytecode is loaded into a fresh {@link ClassLoader}, and the resulting instance is
 * actually invoked — proving the injected calls reach {@code apm-core}'s real {@code Tracer}, not
 * just that the generated bytecode happens to verify.
 */
class JdbcInstrumentationRuleTest {

    private static final String FIXTURE_INTERFACE = "com/example/jdbcapp/FakeJdbcStatement";

    @Test
    void wovenExecuteReturnsTheOriginalValueAndReportsAnOkSpanWithTheSqlTextAttribute() throws Exception {
        CapturingExporter exporter = new CapturingExporter().installAsActiveTracer();
        FakeJdbcStatement instance = loadWovenFixture();

        String result = instance.execute("SELECT * FROM accounts WHERE id = ?");

        assertThat(result).isEqualTo("executed:SELECT * FROM accounts WHERE id = ?");
        assertThat(exporter.exported).hasSize(1);
        SpanData span = exporter.exported.get(0);
        assertThat(span.name()).isEqualTo("JDBC execute");
        assertThat(span.kind()).isEqualTo(SpanKind.CLIENT);
        assertThat(span.status()).isEqualTo(SpanStatus.OK);
        assertThat(span.attributes()).containsEntry("db.statement", "SELECT * FROM accounts WHERE id = ?");
    }

    @Test
    void wovenExecuteUpdateStillThrowsAndReportsAnErrorSpan() throws Exception {
        CapturingExporter exporter = new CapturingExporter().installAsActiveTracer();
        FakeJdbcStatement instance = loadWovenFixture();

        assertThatThrownBy(() -> instance.executeUpdate("DELETE FROM accounts"))
                .isInstanceOf(IllegalStateException.class)
                .hasMessage("boom: DELETE FROM accounts");

        assertThat(exporter.exported).hasSize(1);
        SpanData span = exporter.exported.get(0);
        assertThat(span.name()).isEqualTo("JDBC executeUpdate");
        assertThat(span.status()).isEqualTo(SpanStatus.ERROR);
        assertThat(span.errorMessage()).contains("IllegalStateException").contains("boom: DELETE FROM accounts");
        assertThat(span.attributes()).containsEntry("db.statement", "DELETE FROM accounts");
    }

    @Test
    void aClassThatDoesNotImplementTheTargetInterfaceIsNotTransformedAtAll() {
        CastellanClassFileTransformer transformer =
                new CastellanClassFileTransformer(List.of(new JdbcInstrumentationRule(Set.of(FIXTURE_INTERFACE))));
        byte[] original = WeavingTestSupport.readClassBytes(NotJdbc.class);

        byte[] result = transformer.transform(NotJdbc.class.getClassLoader(),
                "com/example/jdbcapp/NotJdbc", null, null, original);

        assertThat(result).as("transform() must return null (no change) for a non-matching class").isNull();
    }

    private static FakeJdbcStatement loadWovenFixture() throws ReflectiveOperationException {
        CastellanClassFileTransformer transformer =
                new CastellanClassFileTransformer(List.of(new JdbcInstrumentationRule(Set.of(FIXTURE_INTERFACE))));
        byte[] original = WeavingTestSupport.readClassBytes(FakeJdbcStatementTarget.class);

        byte[] woven = transformer.transform(FakeJdbcStatementTarget.class.getClassLoader(),
                "com/example/jdbcapp/FakeJdbcStatementTarget", null, null, original);

        assertThat(woven).as("transform() must actually produce woven bytecode for a matching class").isNotNull();

        Class<?> wovenClass = WeavingTestSupport.defineInFreshClassLoader(FakeJdbcStatementTarget.class, woven);
        return (FakeJdbcStatement) wovenClass.getDeclaredConstructor().newInstance();
    }
}
