package io.castellan.apm.core;

import io.castellan.apm.core.export.LoggingSpanExporter;
import io.castellan.apm.core.sampling.AdaptiveSampler;

/**
 * The one stable, versioned surface that {@code apm-agent}'s woven-in bytecode is allowed to call.
 * Every ASM/ByteByddy transformer in {@code apm-agent} emits calls only to these five static
 * methods — never inlines span-model or sampling logic directly into a target class's bytecode.
 * That split is deliberate and load-bearing for two reasons: (1) it means the actual tracing logic
 * (parenting, sampling, export batching) lives in ordinary Java that {@link Tracer} and friends can
 * unit-test directly, with the bytecode-weaving layer tested separately only for "did it call the
 * bridge with the right arguments at the right point"; (2) it means this method signatures are the
 * only contract a future bytecode-format change or bridge-implementation change has to preserve —
 * every already-woven class in a running JVM keeps working as long as these five signatures don't
 * change, even if everything behind them is rewritten.
 *
 * <h2>Why every parameter/return type here is {@code Object}/{@code String}/{@code Throwable}</h2>
 *
 * Woven bytecode is generated by an ASM transformer that, per class being transformed, may not
 * have {@code io.castellan.apm.core.Span} resolvable in the same way the transformed class's own
 * classloader would resolve it (agent classes are typically loaded by the bootstrap/system
 * classloader and appended to the boot search path so every instrumented class can reach them —
 * see {@code CastellanAgent} — but keeping the *bytecode-level* type of the "span token" local
 * variable as plain {@code java/lang/Object} rather than the concrete {@code Span} type sidesteps
 * ASM's {@code COMPUTE_FRAMES} ever needing to resolve {@code Span}'s type hierarchy at all when
 * computing stack map frames for the injected try/catch — see {@code SpanWeavingMethodVisitor}'s
 * class javadoc in {@code apm-agent} for the full explanation of why that resolution step is the
 * one genuinely dangerous part of {@code COMPUTE_FRAMES}. Using only JDK types here is what makes
 * that whole hazard simply not apply.
 */
public final class AgentBridge {

    private static volatile Tracer tracer = defaultTracer();

    private AgentBridge() {
    }

    private static Tracer defaultTracer() {
        return new Tracer(AdaptiveSampler.withBudget(Double.MAX_VALUE), new LoggingSpanExporter());
    }

    /** Called once by {@code CastellanAgent.premain} to wire in the configured sampler/exporter. Never called from woven bytecode. */
    public static void init(Tracer configuredTracer) {
        tracer = configuredTracer;
    }

    static Tracer activeTracer() {
        return tracer;
    }

    /**
     * Starts a span parented to whatever is already open on this thread (JDBC, outbound HTTP,
     * INTERNAL). Returns an opaque token — {@code null} if the sampler dropped this one — that the
     * woven bytecode must hold in a local variable and pass, unmodified, to {@link #setAttribute}
     * and {@link #end}.
     */
    public static Object start(String kind, String name) {
        return tracer.startSpan(name, SpanKind.valueOf(kind));
    }

    /**
     * Starts a {@code SERVER} span, continuing the caller's trace if {@code traceparentHeader} is a
     * valid W3C {@code traceparent} value (inbound HTTP / Spring MVC entry point), or starting a
     * fresh trace otherwise. {@code traceparentHeader} may be {@code null} (no header present).
     */
    public static Object startWithRemoteParent(String kind, String name, String traceparentHeader) {
        TraceParent remoteParent = traceparentHeader == null
                ? null
                : TraceParent.parse(traceparentHeader).orElse(null);
        return tracer.startSpan(name, SpanKind.valueOf(kind), remoteParent);
    }

    /** No-op when {@code spanToken} is {@code null} (unsampled) — every call site can be unconditional. */
    public static void setAttribute(Object spanToken, String key, String value) {
        if (spanToken instanceof Span span) {
            span.setAttribute(key, value);
        }
    }

    /**
     * The W3C {@code traceparent} value for the span currently open on this thread, formatted and
     * ready to set as an outbound HTTP request header — {@code null} if nothing is open (or the
     * request path was never sampled), in which case outbound instrumentation should simply not
     * set the header rather than propagate a fabricated trace.
     */
    public static String currentTraceparent() {
        return tracer.current()
                .map(span -> TraceParent.sampled(span.traceId(), span.spanId()))
                .map(TraceParent::format)
                .orElse(null);
    }

    /**
     * Ends the span (idempotent, no-op on {@code null}). {@code error} is the {@link Throwable} an
     * instrumented method threw, or {@code null} on a normal return — passing it straight through
     * (rather than pre-digesting it into a boolean/message in the woven bytecode) keeps the
     * bytecode-generation side of an instrumenter trivial: "catch Throwable, call end(span, t),
     * rethrow t" is the entire exception-path shape every transformer emits.
     */
    public static void end(Object spanToken, Throwable error) {
        if (!(spanToken instanceof Span span)) {
            return;
        }
        if (error != null) {
            span.recordError(error);
        }
        tracer.endSpan(span);
    }
}
